# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/juan/Documents/GitHub

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/juan/Documents/GitHub

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/juan/Documents/GitHub/CMakeFiles /home/juan/Documents/GitHub/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/juan/Documents/GitHub/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TestesVant

# Build rule for target.
TestesVant: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestesVant
.PHONY : TestesVant

# fast build rule for target.
TestesVant/fast:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/build
.PHONY : TestesVant/fast

AAKAZE_ANGULOS_VANT.o: AAKAZE_ANGULOS_VANT.cpp.o

.PHONY : AAKAZE_ANGULOS_VANT.o

# target to build an object file
AAKAZE_ANGULOS_VANT.cpp.o:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/AAKAZE_ANGULOS_VANT.cpp.o
.PHONY : AAKAZE_ANGULOS_VANT.cpp.o

AAKAZE_ANGULOS_VANT.i: AAKAZE_ANGULOS_VANT.cpp.i

.PHONY : AAKAZE_ANGULOS_VANT.i

# target to preprocess a source file
AAKAZE_ANGULOS_VANT.cpp.i:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/AAKAZE_ANGULOS_VANT.cpp.i
.PHONY : AAKAZE_ANGULOS_VANT.cpp.i

AAKAZE_ANGULOS_VANT.s: AAKAZE_ANGULOS_VANT.cpp.s

.PHONY : AAKAZE_ANGULOS_VANT.s

# target to generate assembly for a file
AAKAZE_ANGULOS_VANT.cpp.s:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/AAKAZE_ANGULOS_VANT.cpp.s
.PHONY : AAKAZE_ANGULOS_VANT.cpp.s

AAKAZE_VANT.o: AAKAZE_VANT.cpp.o

.PHONY : AAKAZE_VANT.o

# target to build an object file
AAKAZE_VANT.cpp.o:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/AAKAZE_VANT.cpp.o
.PHONY : AAKAZE_VANT.cpp.o

AAKAZE_VANT.i: AAKAZE_VANT.cpp.i

.PHONY : AAKAZE_VANT.i

# target to preprocess a source file
AAKAZE_VANT.cpp.i:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/AAKAZE_VANT.cpp.i
.PHONY : AAKAZE_VANT.cpp.i

AAKAZE_VANT.s: AAKAZE_VANT.cpp.s

.PHONY : AAKAZE_VANT.s

# target to generate assembly for a file
AAKAZE_VANT.cpp.s:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/AAKAZE_VANT.cpp.s
.PHONY : AAKAZE_VANT.cpp.s

AKAZE_VANT.o: AKAZE_VANT.cpp.o

.PHONY : AKAZE_VANT.o

# target to build an object file
AKAZE_VANT.cpp.o:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/AKAZE_VANT.cpp.o
.PHONY : AKAZE_VANT.cpp.o

AKAZE_VANT.i: AKAZE_VANT.cpp.i

.PHONY : AKAZE_VANT.i

# target to preprocess a source file
AKAZE_VANT.cpp.i:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/AKAZE_VANT.cpp.i
.PHONY : AKAZE_VANT.cpp.i

AKAZE_VANT.s: AKAZE_VANT.cpp.s

.PHONY : AKAZE_VANT.s

# target to generate assembly for a file
AKAZE_VANT.cpp.s:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/AKAZE_VANT.cpp.s
.PHONY : AKAZE_VANT.cpp.s

ASIFT_ANGULOS_VANT.o: ASIFT_ANGULOS_VANT.cpp.o

.PHONY : ASIFT_ANGULOS_VANT.o

# target to build an object file
ASIFT_ANGULOS_VANT.cpp.o:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/ASIFT_ANGULOS_VANT.cpp.o
.PHONY : ASIFT_ANGULOS_VANT.cpp.o

ASIFT_ANGULOS_VANT.i: ASIFT_ANGULOS_VANT.cpp.i

.PHONY : ASIFT_ANGULOS_VANT.i

# target to preprocess a source file
ASIFT_ANGULOS_VANT.cpp.i:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/ASIFT_ANGULOS_VANT.cpp.i
.PHONY : ASIFT_ANGULOS_VANT.cpp.i

ASIFT_ANGULOS_VANT.s: ASIFT_ANGULOS_VANT.cpp.s

.PHONY : ASIFT_ANGULOS_VANT.s

# target to generate assembly for a file
ASIFT_ANGULOS_VANT.cpp.s:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/ASIFT_ANGULOS_VANT.cpp.s
.PHONY : ASIFT_ANGULOS_VANT.cpp.s

ASIFT_VANT.o: ASIFT_VANT.cpp.o

.PHONY : ASIFT_VANT.o

# target to build an object file
ASIFT_VANT.cpp.o:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/ASIFT_VANT.cpp.o
.PHONY : ASIFT_VANT.cpp.o

ASIFT_VANT.i: ASIFT_VANT.cpp.i

.PHONY : ASIFT_VANT.i

# target to preprocess a source file
ASIFT_VANT.cpp.i:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/ASIFT_VANT.cpp.i
.PHONY : ASIFT_VANT.cpp.i

ASIFT_VANT.s: ASIFT_VANT.cpp.s

.PHONY : ASIFT_VANT.s

# target to generate assembly for a file
ASIFT_VANT.cpp.s:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/ASIFT_VANT.cpp.s
.PHONY : ASIFT_VANT.cpp.s

ASURF_ANGULOS_VANT.o: ASURF_ANGULOS_VANT.cpp.o

.PHONY : ASURF_ANGULOS_VANT.o

# target to build an object file
ASURF_ANGULOS_VANT.cpp.o:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/ASURF_ANGULOS_VANT.cpp.o
.PHONY : ASURF_ANGULOS_VANT.cpp.o

ASURF_ANGULOS_VANT.i: ASURF_ANGULOS_VANT.cpp.i

.PHONY : ASURF_ANGULOS_VANT.i

# target to preprocess a source file
ASURF_ANGULOS_VANT.cpp.i:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/ASURF_ANGULOS_VANT.cpp.i
.PHONY : ASURF_ANGULOS_VANT.cpp.i

ASURF_ANGULOS_VANT.s: ASURF_ANGULOS_VANT.cpp.s

.PHONY : ASURF_ANGULOS_VANT.s

# target to generate assembly for a file
ASURF_ANGULOS_VANT.cpp.s:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/ASURF_ANGULOS_VANT.cpp.s
.PHONY : ASURF_ANGULOS_VANT.cpp.s

ASURF_VANT.o: ASURF_VANT.cpp.o

.PHONY : ASURF_VANT.o

# target to build an object file
ASURF_VANT.cpp.o:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/ASURF_VANT.cpp.o
.PHONY : ASURF_VANT.cpp.o

ASURF_VANT.i: ASURF_VANT.cpp.i

.PHONY : ASURF_VANT.i

# target to preprocess a source file
ASURF_VANT.cpp.i:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/ASURF_VANT.cpp.i
.PHONY : ASURF_VANT.cpp.i

ASURF_VANT.s: ASURF_VANT.cpp.s

.PHONY : ASURF_VANT.s

# target to generate assembly for a file
ASURF_VANT.cpp.s:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/ASURF_VANT.cpp.s
.PHONY : ASURF_VANT.cpp.s

ORB_VANT.o: ORB_VANT.cpp.o

.PHONY : ORB_VANT.o

# target to build an object file
ORB_VANT.cpp.o:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/ORB_VANT.cpp.o
.PHONY : ORB_VANT.cpp.o

ORB_VANT.i: ORB_VANT.cpp.i

.PHONY : ORB_VANT.i

# target to preprocess a source file
ORB_VANT.cpp.i:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/ORB_VANT.cpp.i
.PHONY : ORB_VANT.cpp.i

ORB_VANT.s: ORB_VANT.cpp.s

.PHONY : ORB_VANT.s

# target to generate assembly for a file
ORB_VANT.cpp.s:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/ORB_VANT.cpp.s
.PHONY : ORB_VANT.cpp.s

SIFT_VANT.o: SIFT_VANT.cpp.o

.PHONY : SIFT_VANT.o

# target to build an object file
SIFT_VANT.cpp.o:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/SIFT_VANT.cpp.o
.PHONY : SIFT_VANT.cpp.o

SIFT_VANT.i: SIFT_VANT.cpp.i

.PHONY : SIFT_VANT.i

# target to preprocess a source file
SIFT_VANT.cpp.i:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/SIFT_VANT.cpp.i
.PHONY : SIFT_VANT.cpp.i

SIFT_VANT.s: SIFT_VANT.cpp.s

.PHONY : SIFT_VANT.s

# target to generate assembly for a file
SIFT_VANT.cpp.s:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/SIFT_VANT.cpp.s
.PHONY : SIFT_VANT.cpp.s

SURF_VANT.o: SURF_VANT.cpp.o

.PHONY : SURF_VANT.o

# target to build an object file
SURF_VANT.cpp.o:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/SURF_VANT.cpp.o
.PHONY : SURF_VANT.cpp.o

SURF_VANT.i: SURF_VANT.cpp.i

.PHONY : SURF_VANT.i

# target to preprocess a source file
SURF_VANT.cpp.i:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/SURF_VANT.cpp.i
.PHONY : SURF_VANT.cpp.i

SURF_VANT.s: SURF_VANT.cpp.s

.PHONY : SURF_VANT.s

# target to generate assembly for a file
SURF_VANT.cpp.s:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/SURF_VANT.cpp.s
.PHONY : SURF_VANT.cpp.s

acuracia.o: acuracia.cpp.o

.PHONY : acuracia.o

# target to build an object file
acuracia.cpp.o:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/acuracia.cpp.o
.PHONY : acuracia.cpp.o

acuracia.i: acuracia.cpp.i

.PHONY : acuracia.i

# target to preprocess a source file
acuracia.cpp.i:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/acuracia.cpp.i
.PHONY : acuracia.cpp.i

acuracia.s: acuracia.cpp.s

.PHONY : acuracia.s

# target to generate assembly for a file
acuracia.cpp.s:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/acuracia.cpp.s
.PHONY : acuracia.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/TestesVant.dir/build.make CMakeFiles/TestesVant.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... TestesVant"
	@echo "... AAKAZE_ANGULOS_VANT.o"
	@echo "... AAKAZE_ANGULOS_VANT.i"
	@echo "... AAKAZE_ANGULOS_VANT.s"
	@echo "... AAKAZE_VANT.o"
	@echo "... AAKAZE_VANT.i"
	@echo "... AAKAZE_VANT.s"
	@echo "... AKAZE_VANT.o"
	@echo "... AKAZE_VANT.i"
	@echo "... AKAZE_VANT.s"
	@echo "... ASIFT_ANGULOS_VANT.o"
	@echo "... ASIFT_ANGULOS_VANT.i"
	@echo "... ASIFT_ANGULOS_VANT.s"
	@echo "... ASIFT_VANT.o"
	@echo "... ASIFT_VANT.i"
	@echo "... ASIFT_VANT.s"
	@echo "... ASURF_ANGULOS_VANT.o"
	@echo "... ASURF_ANGULOS_VANT.i"
	@echo "... ASURF_ANGULOS_VANT.s"
	@echo "... ASURF_VANT.o"
	@echo "... ASURF_VANT.i"
	@echo "... ASURF_VANT.s"
	@echo "... ORB_VANT.o"
	@echo "... ORB_VANT.i"
	@echo "... ORB_VANT.s"
	@echo "... SIFT_VANT.o"
	@echo "... SIFT_VANT.i"
	@echo "... SIFT_VANT.s"
	@echo "... SURF_VANT.o"
	@echo "... SURF_VANT.i"
	@echo "... SURF_VANT.s"
	@echo "... acuracia.o"
	@echo "... acuracia.i"
	@echo "... acuracia.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

